import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
const get=u=>fetch(API+u).then(r=>{if(!r.ok)throw Error("API");return r.json()});
function App(){
 const[tab,setTab]=useState("home"),[online,setOnline]=useState(true),[content,setContent]=useState(),[pass,setPass]=useState(),[verify,setVerify]=useState(),[prov,setProv]=useState(),[answer,setAnswer]=useState(),[journey,setJourney]=useState(),[impact,setImpact]=useState(),[qr,setQr]=useState(),[dash,setDash]=useState();
 useEffect(()=>{Promise.all([get("/health"),get("/api/v1/content/knowledge-001"),get("/api/v1/passports/knowledge-001")]).then(([,c,p])=>{setContent(c);setPass(p)}).catch(()=>setOnline(false))},[]);
 const doVerify=async()=>{setVerify(await get("/api/v1/verify/knowledge-001"));setProv(await get("/api/v1/provenance/knowledge-001"));setTab("passport")};
 const doQR=async()=>setQr((await get("/api/v1/qr/knowledge-001")).data_url);
 const ask=async()=>{setAnswer(await fetch(API+"/api/v1/ai/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content_id:"knowledge-001",question:"ما أصل هذه المادة وما الذي تم التحقق منه؟"})}).then(r=>r.json()));setTab("ai")};
 const learn=async()=>{setJourney(await get("/api/v1/learning/journey-001"));await fetch(API+"/api/v1/learning/journey-001/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event_type:"learning_started"})});setTab("learn")};
 const complete=async()=>{await fetch(API+"/api/v1/learning/journey-001/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event_type:"learning_completed"})});setImpact(await get("/api/v1/impact/knowledge-001"));setTab("athar")};
 const institution=async()=>{setDash(await get("/api/v1/institution/qnl/dashboard"));setTab("institution")};
 return <div className="app"><header><div className="brand" onClick={()=>setTab("home")}><span className="logo">●</span><div><b>أَثَرُهُم</b><small>KNOWLEDGE TRUST INFRASTRUCTURE</small></div></div><nav>{[["home","اكتشف"],["passport","Passport"],["learn","التعلم"],["network","التعاون"],["athar","الأثر"]].map(([x,y])=><button onClick={()=>setTab(x)}>{y}</button>)}</nav><button className="outline" onClick={institution}>للمؤسسات</button></header>
 {!online&&<div className="offline">تعذر الاتصال بالمحرك — الواجهة لن تخترع بيانات.</div>}
 {tab==="home"&&<main className="hero"><label>KNOWLEDGE TRUST INFRASTRUCTURE</label><h1>المعرفة لا تضيع فقط عندما تُنسى.<br/><i>قد تضيع عندما تفقد أصلها.</i></h1><p>أَثَرُهُم يحفظ هوية المعرفة أثناء انتقالها: من المصدر، إلى السند، إلى التحقق، إلى التعلم، ثم إلى الأثر.</p><div className="actions"><button onClick={()=>setTab("passport")}>افتح تجربة المعرفة</button><button className="ghost" onClick={()=>setTab("network")}>شاهد تعاون المؤسسات</button></div><div className="flow">{["المصدر","الهوية","الحقوق","السند","التحقق","AI","التعلم","الأثر"].map((x,n)=><div><small>0{n+1}</small>{x}</div>)}</div></main>}
 {tab==="passport"&&<main className="page"><label>CONTENT PASSPORT</label><h2>{pass?.title}</h2><p>{content?.summary}</p><div className="grid"><section className="card passport"><div className="top"><span>CONTENT ID</span><b>{pass?.content_id}</b></div><div className="facts"><div><small>الجهة</small><b>{pass?.issuer}</b><em>{pass?.issuer_label}</em></div><div><small>الإصدار</small><b>v{pass?.version}</b></div><div><small>الحقوق</small><b>{pass?.license}</b></div><div><small>التكامل</small><b>SHA-256</b><code>{pass?.integrity?.value?.slice(0,18)}…</code></div></div><div className="actions"><button onClick={doVerify}>تحقق وافتح السند</button><button className="ghost" onClick={doQR}>إظهار QR</button></div>{qr&&<img className="qr" src={qr}/>}</section><section className="card"><label>SOURCE</label><h3>{pass?.source?.name}</h3><p>مرجع مصدر — ليست شراكة. حقوق المادة يجب فحصها على مستوى العنصر قبل إعادة الاستخدام.</p><a href={pass?.source?.url} target="_blank">فتح المصدر ↗</a></section></div>{verify&&<section className="card checks"><label>VERIFICATION</label>{verify.checks.map(x=><div><b>✓ {x.label}</b><small>{x.status}</small></div>)}</section>}{prov&&<section className="card"><label>PROVENANCE / SANAD</label><div className="timeline">{prov.nodes.map((x,n)=><div><small>0{n+1}</small><b>{x.label}</b><span>{x.entity}</span></div>)}</div><div className="actions"><button onClick={ask}>اسأل AI مع الدليل</button><button className="ghost" onClick={learn}>ابدأ رحلة التعلم</button></div></section>}</main>}
 {tab==="ai"&&<main className="page"><label>SOURCE-GROUNDED AI</label><h2>الذكاء يخدم السند.</h2><section className="card ai"><blockquote>ما أصل هذه المادة وما الذي تم التحقق منه؟</blockquote><p>{answer?.answer}</p><div className="evidence"><label>EVIDENCE</label>{answer?.evidence?.map(e=><div><b>{e.source}</b><a href={e.url} target="_blank">المصدر ↗</a><small>{e.scope} · {e.reason}</small></div>)}</div><button onClick={learn}>ابدأ التعلم من المصدر</button></section></main>}
 {tab==="learn"&&<main className="page"><label>LEARNING JOURNEY</label><h2>{journey?.title||"من المصدر إلى الأثر"}</h2><p>كل خطوة مرتبطة بالمادة الموثقة، وليست تجربة تعليمية منفصلة عن الأصل.</p>{journey?<>{journey.steps.map((s,n)=><section className="card step"><small>0{n+1}</small><div><b>{s.title}</b><p>{s.description}</p></div><span>→</span></section>)}<button onClick={complete}>إكمال الرحلة وتسجيل الأثر</button></>:<button onClick={learn}>ابدأ الرحلة</button>}</main>}
 {tab==="athar"&&<main className="page"><label>ATHAR ENGINE</label><h2>ماذا حدث للمعرفة بعد أن وصلت إليك؟</h2><p>الأثر ليس رقم مشاهدة فقط؛ إنه سلسلة أحداث قابلة للفهم والتدقيق.</p><div className="metrics">{Object.entries(impact?.metrics||{verified:1,provenance_opened:1,ai_question:0,learning_started:0,learning_completed:0}).map(([k,v])=><div className="card"><small>{k.replaceAll("_"," ")}</small><strong>{v}</strong></div>)}</div><section className="card flow2">المصدر <b>→</b> تحقق <b>→</b> تعلم <b>→</b> أثر</section></main>}
 {tab==="network"&&<main className="page"><label>INSTITUTIONAL COLLABORATION</label><h2>المعرفة يمكن أن تنتقل دون أن تفقد أصلها.</h2><p>مؤسسة تملك الأصل، أخرى تترجم، ثالثة تبني تجربة تعليمية — وكل علاقة موثقة ومربوطة بالمصدر والحقوق.</p><div className="network"><div className="card">Original<small>المصدر</small></div><b>→</b><div className="card">Translation<small>المترجم</small></div><b>→</b><div className="card">Learning<small>المؤسسة التعليمية</small></div></div><section className="card"><h3>Collaboration Request</h3><p>المرحلة التالية تحول هذا العرض إلى سير عمل موافقات كامل.</p><button onClick={async()=>{await fetch(API+"/api/v1/collaborations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content_id:"knowledge-001",role:"translator",note:"طلب ترجمة وفق الحقوق المسجلة"})});alert("تم تسجيل طلب التعاون في السجل.")}}>طلب تعاون</button></section></main>}
 {tab==="institution"&&<main className="page"><label>INSTITUTION WORKSPACE</label><h2>{dash?.organization?.name||"مساحة المؤسسة"}</h2><p>{dash?.organization?.label}</p><div className="metrics">{Object.entries(dash?.metrics||{}).map(([k,v])=><div className="card"><small>{k.replaceAll("_"," ")}</small><strong>{v}</strong></div>)}</div><section className="card"><h3>Knowledge Registry</h3>{dash?.content?.map(c=><div className="registry"><b>{c.title}</b><span>v{c.version}</span><small>{c.license}</small></div>)}</section><section className="card"><h3>Institution Trust Layer</h3><p>هوية · حقوق · Passport · QR · سند · تعاون · AI · تعلم · أثر.</p></section></main>}
 <footer><span>أَثَرُهُم</span><span>Source → Trust → Learning → Athar</span><span>Foundation v0.2</span></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);